# Generated by Django 4.1.4 on 2022-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='Tegs',
            new_name='Teg',
        ),
        migrations.AddField(
            model_name='games',
            name='Description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='ID_GAme',
            field=models.CharField(default='GI', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='Name_of_Game',
            field=models.CharField(default='Name', max_length=128),
            preserve_default=False,
        ),
    ]
