# Generated by Django 4.1.4 on 2022-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_tegs_games_teg_games_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Decription', models.CharField(max_length=10000)),
                ('Price', models.IntegerField(max_length=10000)),
                ('ID_Game', models.CharField(max_length=100)),
            ],
        ),
    ]
