# Generated by Django 4.1.4 on 2022-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
