# Generated by Django 4.1.4 on 2022-12-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_account_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
